#!/usr/bin/env bash

FIJI_PATHS=$FIJI_HOME/ImageJ-linux64:$FIJI_PLUGINS/TomoJ_2.32-jar-with-dependencies.jar:$FIJI_PLUGINS/TomoJ/Eftem_TomoJ_1.03.jar

java -cp $FIJI_PATHS eftemtomoj.EFTEM_TomoJ -tsSignal ./$1 1 1 -tsBg ./$2 2 1 -align NMI 0
