#!/bin/bash

# Execute and print the sequence
echoExec()
{
 COMMAND="$@"
 echo '-->' $COMMAND
 eval $COMMAND
}

fnames=(`ls -d $1/*/`)

echo $fnames

outname=$2
nt=${#fnames[@]}

echo "Number of Folders: $nt"

zoneplate=${3:-25}

counter=0
while [ $counter -lt $nt ]; do
    tomo=${fnames[$counter]}
    echoExec "cd $tomo"
    fusion_file=$(find -name '*_FS.mrc')
    echo $fusion_file
    basename="${fusion_file}" #/${tomo}_FS.mrc"
    echo $basename
    echoExec "matlab -nodisplay -r \"tomo_deconv_wiener(${zoneplate},520,20161201,'${basename}', 10,0.02,20);exit\""

    echoExec "cd ../.."
    let counter=counter+1
done
