#!/bin/bash

srcpath=$1
if [ -z "$1" ]; then
    srcpath="./"
fi

mrc_array=($srcpath/*.mrc)
reference=${mrc_array[0]}
array=${mrc_array[@]/$reference}


echo ${mrc_array[@]}
echo ${reference[@]}
echo ${array[@]}

num_mrcs=${#mrc_array[@]}
echo $num_mrcs


dirname=$(dirname "${reference}")
filename_ref=$(basename $reference)
date=`echo "$filename_ref" | cut -d'_' -f1`
sample=`echo "$filename_ref" | cut -d'_' -f2`


samplename=${dirname}/${date}_${sample}
outname=${samplename}_AVG_norm.mrc

for mrcfile in ${array[@]}; do
    echo "------"
    echo $mrcfile
    if [ ! -f ${outname} ]; then
        eval "scipion xmipp_image_operate ${reference} --plus $mrcfile -o ${outname}"
    else
        eval "scipion xmipp_image_operate ${outname} --plus ${mrcfile}"
    fi
done
eval "scipion xmipp_image_operate ${outname} --divide $num_mrcs"




