#!/usr/bin/env bash

# parameters
FILE_NAME=$1
CROPTYPE=$2

if [ "$1" == "-h" ] ; then
    echo "hdf2normcrop needs two arguments:"
    echo '- a HDF5 tomo file'
    echo '- a Int value to specify with kind of crop:'
    echo '      "1" to apply [0 0 1 0] roi'
    echo '      "2" to apply [26 24 21 20] roi'
    exit 0
fi

if [ $# -lt 2 ]
  then
    echo "Not enough arguments supplied"
    echo "Execute hdf2normcrop -h to show the help "
    exit -1
fi

echo $FILE_NAME, $CROPTYPE
echo "normalize..."
normalize $FILE_NAME

echo "crophdf..."
NORM_FILE_NAME=${FILE_NAME%.*}_norm.hdf5
CROP_FILE_NAME=${FILE_NAME%.*}_norm_crop.hdf5
mv $NORM_FILE_NAME $CROP_FILE_NAME

if [ $CROPTYPE -eq 1 ]
then
    echo "CROP [0 0 1 0]"
    crophdf $CROP_FILE_NAME -r 0 0 1 0 -s TomoNormalized
else
    echo "CROP [26 24 21 20]"
    crophdf $CROP_FILE_NAME -r 26 24 21 19 -s TomoNormalized
fi

