#!/bin/bash

if [ "$HOSTNAME" == "pcbl0906" ]; then
  echo "Executing tomo_deconv in pcbl0906"
  echo "Exporting MATLAB RunTime for pcbl0906"
  export LD_LIBRARY_PATH=/usr/local/MATLAB/MATLAB_Runtime/v90/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v90/bin/glnxa64:$LD_LIBRARY_PATH
fi

# Execute and print the sequence
echoExec()
{
 COMMAND="$@"
 echo '-->' $COMMAND
 eval $COMMAND
}

if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` : deconvolves a single file"
  echo "       - ZP as first argument (default: 25)"
  echo "       - Energy as second argument (default: 520)"
  echo "       - Date as third argument (default: 20170926)"
  echo "       - File name as fourth argument (default: one.mrc)"
  echo "       - DX as fifth argument (default: 12)"
  echo "       - KW as sixth argument (default: 0.02)"
  echo "       - ZSize as seventh argument (default: 20)"
  echo "       - PSF_DIR as eighth argument (default: /beamlines/bl09/controls/user_resources/psf_directory)"
  exit 0
fi


if [ -z "$1" ]; then
    ZP_DR=25
else
    ZP_DR=$1
fi

if [ -z "$2" ]; then
    ENERGY=520
else
    ENERGY=$2
fi

if [ -z "$3" ]; then
    DATE=20170926
else
    DATE=$3
fi

if [ -z "$4" ]; then
    filename="one.mrc"
else
    filename=$4
fi

if [ -z "$5" ]; then
    DX=12
else
    DX=$5
fi

if [ -z "$6" ]; then
    KW=0.02
else
    KW=$6
fi

if [ -z "$7" ]; then
    ZSIZE=20
else
    ZSIZE=$7
fi

if [ -z "$8" ]; then
    PSF_DIR="/beamlines/bl09/controls/user_resources/psf_directory"
else
    PSF_DIR=$8
fi

echo "tomo_deconv_wiener ${ZP_DR} ${ENERGY} ${DATE} ${filename} ${DX} ${KW} ${ZSIZE} ${PSF_DIR}"
tomo_deconv_wiener ${ZP_DR} ${ENERGY} ${DATE} ${filename} ${DX} ${KW} ${ZSIZE} ${PSF_DIR}

