#!/bin/bash


# Rename all files in a folder:
# for FILENAME in *; do mv $FILENAME Unix_$FILENAME; done 

# Execute and print the sequence
echoExec()
{
 COMMAND="$@"
 echo '-->' $COMMAND
 eval $COMMAND
}


txm_txt_file=$1
outdir=$2

echo "xrm2nexus conversion"
xrm2nexus $txm_txt_file --output-dir $outdir --organize-by-repetitions True


echo "Normalizing tomographies"

for hdfrawfile in $( ls ${outdir}/*/*.hdf5 ); do
    echo $hdfrawfile
    normalize $hdfrawfile
done


hdfnormdir=${outdir}/hdfnorm
mkdir -p ${hdfnormdir}
for hdfnormfile in $( ls ${outdir}/*/*_norm.hdf5 ); do
    mv ${hdfnormfile} ${hdfnormdir}
done

cd ./${hdfnormdir}
for hdfnormfile in $( ls ); do
    basefilename=${hdfnormfile%_norm.hdf5}
    mrcnormfile=${basefilename}_norm.mrc
    hdftreeandfile=TomoNormalized/TomoNormalized@${hdfnormfile}
    eval "scipion xmipp_image_convert -i $hdftreeandfile -o $mrcnormfile"
done
cd -


mrcnormdir=${outdir}/mrcnorm
mkdir -p ${mrcnormdir}
for mrcnormfile in $( ls ${hdfnormdir}/*_norm.mrc ); do
    mv ${mrcnormfile} ${mrcnormdir}
done


echo "The fusion has still to be applied"



