#!/bin/bash


# Rename all files in a folder:
# for FILENAME in *; do mv $FILENAME Unix_$FILENAME; done 

# Execute and print the sequence
echoExec()
{
 COMMAND="$@"
 echo '-->' $COMMAND
 eval $COMMAND
}


numimg=$1
srcpath=$2
outdir=$3

hdfoutdir=${outdir}/hdf_mrc_dir

mkdir -p $hdfoutdir
COUNTER=0

## If images begins at 1
#COUNTER=1
#let numimg=numimg+1
## If images begins at 1

while [ $COUNTER -lt $numimg ]; do
    destdir=${outdir}/tomoout_$COUNTER
    echo $destdir
    mkdir -p $destdir

    echo "Copying xrm files to independent folder according the number of image"
    for i in $( ls $srcpath/*_$COUNTER.xrm ); do
        #echo $i
        cp -p $i $destdir
    done
    
    echo "Copying FF files in the same folder"
    for i in $( ls $srcpath/*_FF_* ); do
        #echo $i
        cp -p $i $destdir
    done

    echo "xrm2nexus conversion"
    manytomos2nexus $destdir --output-dir-name $hdfoutdir

    let COUNTER=COUNTER+1
done


echo "Normalizing and croping tomographies"
CROPTYPE=2
for hdfrawfile in $( ls ${hdfoutdir}/*/*.hdf5 ); do
    echo $hdfrawfile
    hdf2normcrop $hdfrawfile $CROPTYPE
done


hdfnormdir=${hdfoutdir}/hdfnorm
mkdir -p ${hdfnormdir}
for hdfnormfile in $( ls ${hdfoutdir}/*/*_norm_crop.hdf5 ); do
    mv ${hdfnormfile} ${hdfnormdir}
done

cd ./${hdfnormdir}
for hdfnormfile in $( ls ); do
    basefilename=${hdfnormfile%_norm_crop.hdf5}
    mrcnormfile=${basefilename}_norm.mrc
    hdftreeandfile=TomoNormalized/TomoNormalized@${hdfnormfile}
    eval "scipion xmipp_image_convert -i $hdftreeandfile -o $mrcnormfile"
done
cd -


mrcnormdir=${hdfoutdir}/mrcnorm
mkdir -p ${mrcnormdir}
for mrcnormfile in $( ls ${hdfnormdir}/*_norm.mrc ); do
    mv ${mrcnormfile} ${mrcnormdir}
done


echo "The fusion has still to be applied"



